### ISSUE TITLE
API Authorization using Strapi Google provider not working.

### ISSUE THREAD

**Issue by rahulkohli23** [strapi/strapi-examples#113]
**Node.js version**:11.12.0

**npm version**:6.9.0

**Strapi version**:3.0.0-alpha.25.2

**Operating system**:Ubuntu 18.04.2 LTS

**Which example is causing problem?**: API Authorization using Google as a provider

**Do you want to request a *feature* or report a *bug*?**:

**What is the current behavior?**:The application returns 
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

**If the current behavior is a bug, please provide the steps to reproduce the problem**:
1) Clone the Login-React project from the below repository.
https://github.com/strapi/strapi-examples.
2) download the dependencies using npm install.
3) run the application using npm start(The app will run on http://localhost:3000).
4) run the strapi my-project (hosted on localhost:1337).
2) Follow The Steps as per the document 
https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md

**What is the expected behavior?**:
Instead of giving a google login page.
the URI returns 
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

![image](https://user-images.githubusercontent.com/40965683/60798056-0ef6e400-a18e-11e9-8141-5ef87cedb924.png)

After clicking the Google Button it redirects to the following page.

![image](https://user-images.githubusercontent.com/40965683/60798161-38177480-a18e-11e9-9885-9a0d89c5a44c.png)

**Comment by muhaimincs** [comment]
try to update to beta version

**Comment by AurelienVernay** [comment]
I'm using strapi 3.0.0-alpha.26.1, and i'm having difficulties to set up google authentication using strapi provider as well, but i don't think this is related to Strapi version.
When i'm putting `http://localhost:1337/connect/google/callback` as an allowed redirection URI, i get the following error from Google : 

![image](https://user-images.githubusercontent.com/18377871/61713714-7cdc0780-ad59-11e9-90f8-c779bc2b9357.png)

Below is my google OAuth web config : 
![image](https://user-images.githubusercontent.com/18377871/61713756-94b38b80-ad59-11e9-8ab2-45822e28ee61.png)

How to test the google Authentication API when developing if `localhost` isn't supported ?

**Comment by AurelienVernay** [comment]
Try to debug node server.js and look at `Auth.js` in `plugins/user-permissions/controllers` at line 154 : it may be Google API silently failing (i had a similar issue because i didn't activate Google + API

**Comment by lauriejim** [comment]
This issue is fixed since we release the `beta.14` version of strapi.
Please check the changelog here https://github.com/strapi/strapi/releases/tag/v3.0.0-beta.14
You will be able to find the PR that did the fix and apply changes to your application is you don't or can't update to the last version of strapi.

**Comment by rahulkohli23** [comment]
it's working when installed the new beta version
Thanks, everybody for help
