### ISSUE TITLE
how to add one to many relations for two content types?

### ISSUE THREAD

**Issue by chandrapenumarthi** [strapi/strapi-examples#13]
**Node.js version**: v8.9

**npm version**:5.5

**Strapi version**:3.0.0-alpha

**Operating system**:Ubuntu

**Which example is causing problem?**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by soupette** [comment]
Hi could you be more specific on what you're trying to achieve? Which example or boilerplate are you referring to?

Thanks!

**Comment by chandrapenumarthi** [comment]
gatsby-strapi-tutorial - this is the code I am referring.
I created new content type "contact" and I want to make a one-to-many relation between user and contact.
Can you please suggest how to achieve above?

**Comment by pierreburgy** [comment]
@chandrapenumarthi you have two options to create a relation:
 - Use the Content Type Builder in Strapi admin panel: add a new field with the type "Relation".
 - Edit your models files (https://strapi.io/documentation/guides/models.html).

**Comment by DonLduk** [comment]
> @chandrapenumarthi you have two options to create a relation:
> 
> * Use the Content Type Builder in Strapi admin panel: add a new field with the type "Relation".
> * Edit your models files (https://strapi.io/documentation/guides/models.html).

Hi. I have a question regarding these steps. I managed to create a city, and some users. I need to relate several users to a city. I can do it by "Content Type Builder", and I see the related fields (this is ok). But when I query from the front-end, I don't have the relation. 

for example, how do I bring all the users within a city? .

**Comment by ifeatu** [comment]
+1

**Comment by Cignite** [comment]
I got same question as @DonLduk
