### ISSUE TITLE
gatsbi-strapi-tutorial setup fails during npm install sharb@0.22.0

### ISSUE THREAD

**Issue by ragamroll** [strapi/strapi-examples#133]
**Node.js version**:
12.6.0

**npm version**:
6.11.3

**Strapi version**:
3.0.0-aplha.25.2

**Operating system**:
Ubuntu 16.04.6 LTS

**Which example is causing problem?**
gatsby-strapi-tutorial

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
:~/dev/git/strapi-examples/gatsby-strapi-tutorial/cms$ ls
admin  config       node_modules  plugins  README.md
api    favicon.ico  package.json  public   server.js
mani@vdi:~/dev/git/strapi-examples/gatsby-strapi-tutorial/cms$ cd ..
mani@vdi:~/dev/git/strapi-examples/gatsby-strapi-tutorial$ ls
blog  cms  content-for-tutorial  README.md
mani@vdi:~/dev/git/strapi-examples/gatsby-strapi-tutorial$ cd blog
mani@vdi:~/dev/git/strapi-examples/gatsby-strapi-tutorial/blog$ ls
gatsby-browser.js  gatsby-node.js  LICENSE       package-lock.json  src
gatsby-config.js   gatsby-ssr.js   package.json  README.md          yarn.lock
mani@vdi:~/dev/git/strapi-examples/gatsby-strapi-tutorial/blog$ npm install

> sharp@0.22.0 install /home/mani/dev/git/strapi-examples/gatsby-strapi-tutorial/blog/node_modules/gatsby-plugin-manifest/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.7.4/libvips-8.7.4-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=12.6.0 runtime=node arch=x64 libc= platform=linux)
make: Entering directory '/home/mani/dev/git/strapi-examples/gatsby-strapi-tutorial/blog/node_modules/gatsby-plugin-manifest/node_modules/sharp/build'
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
In file included from ../src/common.cc:27:0:
../src/common.h:80:16: error: ‘Handle’ is not a member of ‘v8’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                ^
../src/common.h:80:37: error: expected primary-expression before ‘>’ token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                     ^
../src/common.h:80:39: error: ‘obj’ was not declared in this scope
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                       ^
../src/common.h:80:56: error: expected primary-expression before ‘attr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                        ^
../src/common.h:80:60: error: expression list treated as compound expression in initializer [-fpermissive]
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
                                                            ^
../src/common.h:81:25: error: ‘Handle’ is not a member of ‘v8’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                         ^
../src/common.h:81:46: error: expected primary-expression before ‘>’ token
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                              ^
../src/common.h:81:48: error: ‘obj’ was not declared in this scope
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                ^
../src/common.h:81:65: error: expected primary-expression before ‘attr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
                                                                 ^
../src/common.h:82:34: error: ‘Handle’ is not a member of ‘v8’
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
                                  ^
../src/common.h:82:55: error: expected primary-expression before ‘>’ token
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
                                                       ^
../src/common.h:82:57: error: ‘obj’ was not declared in this scope
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
                                                         ^
../src/common.h:82:74: error: expected primary-expression before ‘attr’
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
                                                                          ^
../src/common.h:83:44: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::str
                                            ^
../src/common.h:83:65: error: expected primary-expression before ‘>’ token
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::str
                                                                 ^
../src/common.h:83:67: error: ‘obj’ was not declared in this scope
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::str
                                                                   ^
../src/common.h:83:84: error: expected primary-expression before ‘attr’
 typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                         ^
../src/common.h:83:37: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::str
                                     ^
../src/common.h:83:90: error: expected ‘;’ before ‘{’ token
 typename T> v8::Local<T> AttrAs(v8::Handle<v8::Object> obj, std::string attr) {
                                                                               ^
../src/common.h:86:33: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                 ^
../src/common.h:86:54: error: expected primary-expression before ‘>’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                      ^
../src/common.h:86:56: error: ‘obj’ was not declared in this scope
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                        ^
../src/common.h:86:73: error: expected primary-expression before ‘attr’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                         ^
../src/common.h:86:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                          ^
../src/common.h:86:79: error: expected ‘;’ before ‘{’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                                                                               ^
../src/common.h:89:33: error: ‘Handle’ is not a member of ‘v8’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                 ^
../src/common.h:89:54: error: expected primary-expression before ‘>’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                      ^
../src/common.h:89:56: error: ‘obj’ was not declared in this scope
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                        ^
../src/common.h:89:61: error: expected primary-expression before ‘int’
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                             ^
../src/common.h:86:26: warning: variable templates only available with -std=c++14 or -std=gnu++14
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, std::string attr) {
                          ^
../src/common.h:89:71: error: expected ‘;’ before ‘{’ token
   template<typename T> T AttrTo(v8::Handle<v8::Object> obj, int attr) {
                                                                       ^
../src/common.h:95:5: error: ‘Handle’ is not a member of ‘v8’
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersTo
     ^
../src/common.h:95:26: error: expected primary-expression before ‘>’ token
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersTo
                          ^
../src/common.h:95:28: error: ‘input’ was not declared in this scope
     v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersTo
                            ^
../src/common.h:95:70: error: expected primary-expression before ‘&’ token
    v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToP
                                                                     ^
../src/common.h:95:71: error: ‘buffersToPersist’ was not declared in this scope
   v8::Handle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPe
                                                                     ^
../src/common.h:95:87: error: expression list treated as compound expression in initializer [-fpermissive]
 andle<v8::Object> input, std::vector<v8::Local<v8::Object>> &buffersToPersist);
                                                                              ^
../src/common.cc:34:20: error: redefinition of ‘bool sharp::HasAttr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                    ^
In file included from ../src/common.cc:27:0:
../src/common.h:80:8: note: ‘bool sharp::HasAttr’ previously defined here
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr);
        ^
../src/common.cc:34:16: error: ‘Handle’ is not a member of ‘v8’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                ^
../src/common.cc:34:37: error: expected primary-expression before ‘>’ token
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                     ^
../src/common.cc:34:39: error: ‘obj’ was not declared in this scope
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                       ^
../src/common.cc:34:56: error: expected primary-expression before ‘attr’
   bool HasAttr(v8::Handle<v8::Object> obj, std::string attr) {
                                                        ^
../src/common.cc:37:29: error: redefinition of ‘std::string sharp::AttrAsStr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                             ^
In file included from ../src/common.cc:27:0:
../src/common.h:81:15: note: ‘std::string sharp::AttrAsStr’ previously declared here
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr);
               ^
../src/common.cc:37:25: error: ‘Handle’ is not a member of ‘v8’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                         ^
../src/common.cc:37:46: error: expected primary-expression before ‘>’ token
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                              ^
../src/common.cc:37:48: error: ‘obj’ was not declared in this scope
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                ^
../src/common.cc:37:65: error: expected primary-expression before ‘attr’
   std::string AttrAsStr(v8::Handle<v8::Object> obj, std::string attr) {
                                                                 ^
../src/common.cc:40:38: error: redefinition of ‘std::vector<double> sharp::AttrAsRgba’
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) 
                                      ^
In file included from ../src/common.cc:27:0:
../src/common.h:82:23: note: ‘std::vector<double> sharp::AttrAsRgba’ previously declared here
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr);
                       ^
../src/common.cc:40:34: error: ‘Handle’ is not a member of ‘v8’
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) 
                                  ^
../src/common.cc:40:55: error: expected primary-expression before ‘>’ token
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) 
                                                       ^
../src/common.cc:40:57: error: ‘obj’ was not declared in this scope
   std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) 
                                                         ^
../src/common.cc:40:74: error: expected primary-expression before ‘attr’
  std::vector<double> AttrAsRgba(v8::Handle<v8::Object> obj, std::string attr) {
                                                                         ^
../src/common.cc:669:1: error: expected ‘}’ at end of input
 }  // namespace sharp
 ^
cc1plus: warning: unrecognized command line option ‘-Wno-cast-function-type’
sharp.target.mk:134: recipe for target 'Release/obj.target/sharp/src/common.o' failed
make: *** [Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/home/mani/dev/git/strapi-examples/gatsby-strapi-tutorial/blog/node_modules/gatsby-plugin-manifest/node_modules/sharp/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mani/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-58-generic
gyp ERR! command "/home/mani/.nvm/versions/node/v12.6.0/bin/node" "/home/mani/.nvm/versions/node/v12.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mani/dev/git/strapi-examples/gatsby-strapi-tutorial/blog/node_modules/gatsby-plugin-manifest/node_modules/sharp
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.22.0 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.22.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mani/.npm/_logs/2019-09-12T08_14_36_279Z-debug.log
~/dev/git/strapi-examples/gatsby-strapi-tutorial/blog$ 

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**
https://github.com/strapi/strapi-examples/tree/master/gatsby-strapi-tutorial#setup-and-live-example-start

**Comment by bketelsen** [comment]
I got past this by downgrading to node 10
