### ISSUE TITLE
Facebook login does not direct to logged page

### ISSUE THREAD

**Issue by Marcosul** [strapi/strapi-examples#140]
Hello

**Node.js version**:
v10.16.3

**npm version**:
6.9.0

**Strapi version**:
3.0.0-beta.17.8

**Operating system**:
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I configured the login-react / react-login-front-end-app sample project to authenticate with Facebook, ran it and apparently it worked. However, after authenticated, the front shows the authentication data (response payload) as shown below and does not redirect to the login screen.

**What is the expected behavior?**
To redirect to the logged in page.

What is missing to do to redirect to the logged page same as login via email?

![image](https://user-images.githubusercontent.com/4714018/70850853-977c5d80-1e6d-11ea-8ab2-ef96656bd047.png)

**Comment by lauriejim** [comment]
Hello! Please make sure well followed the documentation to configure your app.
Just tested and it works well.

**Comment by AnthonyPhan** [comment]
Hi @Marcosul  did you manage to resolve this issue? I too am experiencing this issue. 
Tested with Microsoft and Google providers

**Comment by AnthonyPhan** [comment]
Hi @Marcosul ,

I was able to resolve this issue, hopefully this post helps other to also resolve the issue.

When enabling the provider with strapi's admin panel be very carefull to set the correct "Redirect URL for front-end app". By default this field will be populated by strapi to the incorrect port (1337). The example code provided is configured to run on port 3000. 

Manually changing the redirect url to port 3000 will resolve this issue.
 
![image](https://user-images.githubusercontent.com/12785492/78567613-89ef4700-7853-11ea-9614-d6015bf50bb3.png)

**Comment by aravinddesign** [comment]
HI @AnthonyPhan 

I am facing the same issue. I have tied changing the port name to 3000.
`http://localhost:300/auth/google/callback`

But I get a blank page after I did google authentication. Can you help me with how you resolved it?
