### ISSUE TITLE
building the project using the repository does not seem work

### ISSUE THREAD

**Issue by Zenahr** [strapi/strapi-examples#141]
Sorry if this isn't the right place to ask this. If that's the case, please feel free to refer me to the right place.

I've been following the youtube tutorials, redo the project 3x-4x times following the written tutorial, finally gave up for now and cloned the final git rep, ran the commands as stated in the README and still ended up with a unusable code-base.

The errors I get are:
(After running "gatsby develop"):
The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.

 ERROR 

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

 ERROR 

UNHANDLED REJECTION Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

**Comment by ZenaMel** [comment]
@derrickmehaffy I'm guessing this is closed since the issue has been solved?

**Comment by derrickmehaffy** [comment]
We archived that example so we closed all issues with the archived stuff. We don't own the Gatsby Strapi source package anymore and we don't really do any testing with Gatsby either.
