### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by JurajJakubov** [strapi/strapi-examples#143]
Hello,

i want to ask if is possible to upgrade https://github.com/strapi/strapi-examples/tree/master/nextjs-react-strapi-deliveroo-clone-tutorial this example to newest nextjs and node version because it nextjs is widely used and probably a lot of developers will need it. Its really awesome job but it need som care now.

Thanks for your time.
Juraj

**Comment by Mcastres** [comment]
Hello @JurajJakubov  

We are going to update this tutorial in a month or two approximatively and it will be available on the new tutorials repository: https://github.com/strapi/strapi-tutorials/tree/master/tutorials

We made another Next.js tutorial for creating a simple blog if you want: https://github.com/strapi/strapi-tutorials/tree/master/tutorials/next-strapi-apollo-blog

Have fun with Strapi!
