### ISSUE TITLE
Server wasn't able to start properly. error Invalid empty username provided

### ISSUE THREAD

**Issue by v-osnovnom-bezvreden** [strapi/strapi-examples#144]
**Node.js version**:
v12.16.1

**npm version**:
6.13.4

**Strapi version**:
strapi@3.0.0-beta.19.3

**Operating system**:
Linux kubuntu 5.3.0-40-generic 

**Which example is causing problem?**
cheesecakes 

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
server does not start

**If the current behavior is a bug, please provide the steps to reproduce the problem**

Follow instruction 
On step 5  of readme there is an   error:

```
-> % npm start

> cheesecakes@ start /home/mart/git/strapi-examples/cheesecakes
> node server.js


[2020-03-12T05:04:21.359Z] debug ⛔️ Server wasn't able to start properly.
[2020-03-12T05:04:21.360Z] error Invalid empty username provided
Invalid empty username provided
```

**What is the expected behavior?**
server must start

**Comment by lauriejim** [comment]
Hello, we will remove this example.
Please check this repo instead - https://github.com/strapi/foodadvisor

**Comment by kremerNK** [comment]
this example is still up. maybe it can be replaced with the one mentioned above so people don't spend time on cheesecakes

**Comment by derrickmehaffy** [comment]
Marking as closed as the error referenced is for an old example.
