### ISSUE TITLE
missing dll file? 

### ISSUE THREAD

**Issue by wcousin** [strapi/strapi-examples#153]
Node.js version: 14.3

npm version: 6.14.5

Operating system: Mac OS

My issue is running the login-react app. I get the following error when I run 'npm start':

The DLL manifest is missing. Please run `npm run build:dll`

When I run 'npm run build:dll' it asks if I want to install webpack CLI. Regardless of if I pick 'yes' or 'no', it stalls at this point.

**Comment by RileyMShea** [comment]
You will almost assuredly have issues trying to use node version 14.x with any of these examples(and any React project for the near future) as it is not the current LTS (version 12 is).

First off  I would switch nodejs to version 12 as that is the current nodejs LTS.  I'd personally uninstall 14 completely then install v12, but `nvm` is option if you need v14 for other projects. Trying to get any react project to work with nodejs v14 is probably a nightmare scenario.

In this case however it sounds like you may not have installed the the project dependendencies.

First I would remove your existing `node_modules` folder in the project folder (if it exists)

`rm -rf node_modules`

You *should* then be able to simply:

```bash
# At project root directory(this will run build:dll after main dependency installation)
npm install
# after that finishes npm run start should work
npm run start
```

**Comment by wcousin** [comment]
Thank you. That helped the dll file issue. I still get the following error:

Error: Plugin could not be registered at 'html-webpack-plugin-before-html-generation'. Hook was not found.
BREAKING CHANGE: There need to exist a hook at 'this.hooks'. To create a compatibility layer for this hook, hook into 'this._pluginCompat'. It has something to do with 'tapable' in node_modules.

I'm now running node 12.16.3.

**Comment by wcousin** [comment]
I just deleted the entire repo and started over. Here are the exact errors when installing this with npm install:

`npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.3","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.3","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN react-boilerplate@ No repository field.

added 1752 packages from 883 contributors and audited 1759 packages in 37.728s

27 packages are looking for funding
  run `npm fund` for details

found 1414 vulnerabilities (560 low, 41 moderate, 813 high)
  run `npm audit fix` to fix them, or `npm audit` for details`
