### ISSUE TITLE
Issues installing and running 'login-react'

### ISSUE THREAD

**Issue by wcousin** [strapi/strapi-examples#154]
**Node.js version**: 12.16.3

**npm version**: 6.14.5

**Operating system**: MacOS Catalina Version 10.15.4 

I just deleted the entire repo and started over. Here are the exact errors when installing this with npm install:

`npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.16.3","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.3","npm":"6.14.5"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN react-boilerplate@ No repository field.

added 1752 packages from 883 contributors and audited 1759 packages in 37.728s

27 packages are looking for funding
run npm fund for details

found 1414 vulnerabilities (560 low, 41 moderate, 813 high)
run npm audit fix to fix them, or npm audit for details`

When I run 'npm audit fix' there are still over 100 issues that need to be reviewed manually with 'npm audit'.

Then when I run 'npm start' I get the following error:

`react-boilerplate@ start /Users/wcousin/Desktop/webApps/strapi-examples/login-react/react-login-front-end-app
> cross-env NODE_ENV=development node server

The DLL manifest is missing. Please run `npm run build:dll``

**Comment by alexon1234** [comment]
Try https://github.com/strapi/strapi-examples/pull/149/files
If not you can check it https://codesandbox.io/s/github/strapi/strapi-examples/tree/master/login-react/react-login-front-end-app
