### ISSUE TITLE
Providers: Incomplete field "The redirect URL to add in your Google application configurations"

### ISSUE THREAD

**Issue by jonathanmach** [strapi/strapi-examples#159]
**Node.js version**:
v12.18.0
**npm version**:
6.14.4
**Strapi version**:
"strapi": "3.0.4",
**Operating system**:
Windows 10

**Which example is causing problem?**
All the documentation I've read https://github.com/strapi/strapi-examples/issues/18#issuecomment-382781359) shows the *The redirect URL to add in your Google application configurations* field (which cannot be edited) starting with `http://localhost:1337....`
Mine, however, appears like shown in the picture (`/connect/google/callback`).
I believe that's why I'm having trouble with Google Auth integration

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/12788052/85638328-8793d080-b67d-11ea-90fe-859a5702e999.png)

**What is the expected behavior?**
I'm expecting to view the *The redirect URL to add in your Google application configurations* field starting with `http://localhost:1337....` as shown here: https://github.com/strapi/strapi-examples/issues/18#issuecomment-382781359.

**Comment by JBobeldyk** [comment]
I had the same issue and was able to partially resolve it using some of the advice from https://github.com/strapi/strapi/issues/6570

In `strapi.config.server` I added `url: 'http://localhost:1337'`
The redirect URL still only has /connect/google/callback but now the redirect URL is correct when doing the demo and I can use google auth to log in

**Comment by jonathanmach** [comment]
Thanks!
I also came across that Issue and did as suggested. It is also working fine now.
