### ISSUE TITLE
frontend shouldn't decide of the order price

### ISSUE THREAD

**Issue by ggirodda** [strapi/strapi-examples#165]
**Node.js version**:

**npm version**:

**Strapi version**:

**Operating system**:

**Which example is causing problem?**
nuxt-strapi-deliveroo-clone-tutorial
**Do you want to request a *feature* or report a *bug*?**
report a bad implementation
**What is the current behavior?**
the frontend push the final price directly in db
**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**
the frontend should only push items, the price has to be computed or at least verified on backend

**Comment by eriskhan** [comment]
As for me, it's meant to be a tutorial, not a final solution. So that obviously requires some work from the developer's side
