### ISSUE TITLE
Google OAuth Provider Issue

### ISSUE THREAD

**Issue by JeffWeim** [strapi/strapi-examples#18]
**Node.js version**:
9.11.1

**npm version**:
5.4.2

**Strapi version**:
3.0.0-alpha.11.3

**Operating system**:
MacOS

**Which example is causing problem?**
good-old-react-authentication-flow

**Do you want to request a *feature* or report a *bug*?**
report a *bug*

**What is the current behavior?**
After enabling Google as an OAuth provider in the Strapi admin, I attempt to use the provider for a login. I click the Google button and in the client receive this message: `{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}`. Looking at the server output the only error I'm seeing is simply: `error undefined is not a function` along with the GET request

**If the current behavior is a bug, please provide the steps to reproduce the problem**
1. In the admin, enable Google as an OAuth Provider
2. Input your client ID and client secret
3. Leave *The redirect URL to your front-end app* and *The redirect URL to add in your Google application configurations* as is
4. return to the client and go to `/auth/login`
5. Attempt a login with Google

An additional note is that after configuring the Provider settings correctly, I was able to reach the Google account selection page. However, I am now only receiving the `{"message":"An internal server error occurred","statusCode":500,"error":"Internal Server Error"}` error in the client

**What is the expected behavior?**
Go to Google account selection, be returned to logged in state within the app

**Comment by JeffWeim** [comment]
@soupette 

First, I've found that the issue was simply not having the Google+ API enable. I feel like for the `development` env, there needs to be much better debug messaging enabled. This was a simple issue to fix, but there was nothing indicating what needed to happen.

Second, I'm now receiving another message in the client. It is happening on the redirect back from Google to the app. The message reads:

```json
{
   "jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNTIzNjQwNjYyLCJleHAiOjE1MjYyMzI2NjJ9.Lp0bELpbJaYqSC6YSj1PNIyXHzYWVhvF4GrDxAiItJY",
   "user":{
      "id":3,
      "username":"email@here.com",
      "email":"email@here.com",
      "provider":"google",
      "role":{
         "id":3,
         "name":"Public",
         "description":"Default role given to unauthenticated user.",
         "type":"public"
      },
      "updated_at":null,
      "created_at":null
   }
}
```

I'm not sure why at this point the client isn't returning to the app in a logged-in state

**Comment by soupette** [comment]
I think that you'll find answer in this [documentation](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md).

Let me know if you're still struggling

**Comment by JeffWeim** [comment]
@soupette 

If I follow the steps in those docs, I'm continually redirected back to Google account selection page (ie `https://accounts.google.com/signin/oauth/oauthchooseaccount...`)

I'm confused as to why in the docs for the "**The redirect URL to your front-end app**" section it says to use `connect/google`, while the default value in the admin is `auth/google/callback`.

Neither of the values seem to work

**Comment by soupette** [comment]
If you're using the boilerplate provided in the examples it's  `http://locahost:3000/connect/google`.

You're right, the url writtent in the admin is wrong but if you click on the field you'll see that it will automatically change to `auth/google/callback` so you need to edit this field in the admin.

**Comment by soupette** [comment]
Well the redirect URL of your front-end app can be changed, However the one that manages the authentication between your api and your provider cannot be modified since it's dynamic, so if you change the port of your API the field will also be updated

**Comment by JeffWeim** [comment]
Hmm alright. So how is it in this [documentation](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md) you were able to set both `http://locahost:3000` and `http://localhost:1337`?

![admin_google_conf](https://user-images.githubusercontent.com/8635521/39002016-726a9130-43ac-11e8-8292-af48b62c5ab1.png)

This is what I'm most confused about.

**Comment by nabiltkarim** [comment]
@JeffWeim facing the same issues here while trying to integrating it with my strapi admin. Any clues as to what values you put as redirect URL in your provider?

**Comment by pronvd7** [comment]
you need to make google process firstly from frontend app after that response add to the strapi backend server
