### ISSUE TITLE
Readme Setup - git clone permission error

### ISSUE THREAD

**Issue by BenRinthLabs** [strapi/strapi-examples#191]
**What is the current behavior?**

<img width="1435" alt="image" src="https://github.com/strapi/strapi-examples/assets/25337335/0a70b694-f33b-4b08-a6f0-b52d3031ca5e">

`git clone git@github.com:strapi/strapi-examples.git`

causes this error:
```
Cloning into 'strapi-examples'...
The authenticity of host 'github.com (140.82.113.4)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

<img width="685" alt="image" src="https://github.com/strapi/strapi-examples/assets/25337335/f8400d3d-dc05-4057-ac54-2493b5aa7f8b">

The command should be:
`git clone https://github.com/strapi/strapi-examples.git`

<img width="721" alt="image" src="https://github.com/strapi/strapi-examples/assets/25337335/e2741ea6-0139-47cd-888d-d0f6fb796216">

**Comment by derrickmehaffy** [comment]
This isn't an issue with this repo, it's your ssh key which we can't do anything about.
