### ISSUE TITLE
Can´t clone the repository

### ISSUE THREAD

**Issue by lddd** [strapi/strapi-examples#20]
> ubuntu@ip-172-31-61-13:~$ sudo git clone https://github.com/strapi/sample-strapi-app
> Cloning into 'sample-strapi-app'...
> Username for 'https://github.com':xxx
> Password for 'https://xxx@github.com':
> remote: Repository not found.
> fatal: repository 'https://github.com/strapi/sample-strapi-app/' not found
> ubuntu@ip-172-31-61-13:~$ remote: Repository not found.

Also why does it ask to auth at all?

**Comment by soupette** [comment]
Did you manage to clone the repository?
