### ISSUE TITLE
Could not find jekyll-strapi-0.1.1 in any of the sources

### ISSUE THREAD

**Issue by yummyelin** [strapi/strapi-examples#25]
**Node.js version**: 9.10.1

**npm version**:5.6.0

**Strapi version**:3.0.0-alpha.12.2

**Operating system**:macOS

**Which example is causing problem?**
jekyll-strapi-tutorial

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Can't start Jekyll server.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
Operating system is macOS, didn't install bundler, jekyll-strapi, latest ruby before.

1. Following README, run 
`cd api && npm install && npm start`,
success, Strapi server started.
2. Following README, run 
`cd blog && bundle install && bundle exec jekyll serve`, 
said: bundle: command not found
3. Run 
`gem install bundler`, and 
`bundle install`, 
said: Could not find jekyll-strapi-0.1.1 in any of the sources.
4. Run 
`gem install jekyll-strapi`, 
said: public_suffix requires Ruby version >= 2.1.
5. Run 
`rvm install ruby-2.1`, and 
`gem install jekyll-strapi`, 
said: ruby_dep requires Ruby version >= 2.2.5, ~> 2.2.
6. Run 
`rvm install ruby-head`, and 
`gem install jekyll-strapi`, 
said: Successfully installed jekyll-strapi-0.1.2.
7. Run 
`bundle install && bundle exec jekyll serve`, 
said: Could not find jekyll-strapi-0.1.1 in any of the sources.
8. Run 
`gem install jekyll-strapi-0.1.1`,
 said: Could not find a valid gem 'jekyll-strapi-0.1.1' (>= 0) in any repository.
9. Go back to step 4.

Have no idea how to continue.

**What is the expected behavior?**
I expect I can follow README to run this example.

Please provide a complete README to avoid above headache, and help solve 'Could not find a valid gem 'jekyll-strapi-0.1.1' (>= 0) in any repository' error.

**Comment by jatin69** [comment]
exactly same bug. The readme needs to contain complete information.

**Comment by lauriejim** [comment]
https://github.com/strapi/strapi-examples/pull/91
