### ISSUE TITLE
Facebook Provider doesn't work with HTTPS

### ISSUE THREAD

**Issue by ClementLoridan** [strapi/strapi-examples#27]
**Node.js version**: v8.9.4

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.12.2

**Operating system**: OSX 10.12.6

I have a problem with Facebook Provider:

I use login-react example (localhost:3000) and my API Strapi (https://api.myexample.com in local).
I use https in local because Facebook developer doesn't accept URI url is not https

But the redirect is incorrect : http://localhost:3000/auth/facebook/callback?access_token=...

I think that redirect would be : /auth/facebook/callback?code=...

I change this in Auth.js (users-permissions)

```
server: {
        protocol: 'https',
        host: 'myexample.com'
      }
```

I don't know why ... Help please 

Thk

PS: Not working with other Provider.

**Comment by soupette** [comment]
@ClementLoridan can you follow these [steps](https://github.com/strapi/strapi-examples/blob/master/login-react/doc/fb_setup.md) to enable FB.

I tried on Monday and it was working (even without https).

Also the redirect URL should be http://localhost:3000/connect/facebook

and one Facebook side http://localhost:1337/connect/facebook/callback

**Comment by xeastcrast** [comment]
@soupette But it wasn't working for me now. I think because FB has force https now.
I can't use this URL
http://localhost:3000/connect/facebook
http://localhost:1337/connect/facebook/callback

I was very hard tried for this but It not working

**Comment by xeastcrast** [comment]
@soupette Yes i tried

**Comment by soupette** [comment]
Is it working?

**Comment by xeastcrast** [comment]
@soupette No I can't save this url http://localhost:3000/connect/facebook
http://localhost:1337/connect/facebook/callback

facebook warning me that "only support https url"

**Comment by diamondback15** [comment]
I have to same issue right now. I want to use facebook login in production and the callback always redirect to : http://api.example.com instead of https://api.example.com

**Comment by eugenio10cervantes** [comment]
i just changed the proxy config in /config/environments/production/server.json... looks like this

{
  "host": "mystrapidomain.com",
  "production": true,
  "proxy": {
    "enabled": true,
        "host": "mystrapidomain.com",
        "ssl": true
  },
  "cron": {
    "enabled": false
  },
  "admin": {
    "autoOpen": false
  }
}
