### ISSUE TITLE
You shouldn't trust user input on the price

### ISSUE THREAD

**Issue by udox-cameron** [strapi/strapi-examples#29]
You should query the database and calculator the total in this method. This is the way I did it with using Stripe and Firebase.

```
const orderData = queryOrder.data()
const productsPromise = orderData.items.map(item => database.collection('products').doc(item.id).get())
const products = await Promise.all(productsPromise)
const amount = products.reduce(( total, current ) => {
	const currentProduct = orderData.items.find(product => product.id === current.id)
	return (current.data().price * currentProduct.quantity) + total
}, 0)
```

https://github.com/strapi/strapi-examples/blob/77d69b63f6eb70d05c01731d17013a1f2f3ae8ea/nuxt-strapi-deliveroo-clone-tutorial/server/api/order/controllers/Order.js#L65

**Comment by lauriejim** [comment]
Hello @udox-cameron, can you submit a PR with your update please.

**Comment by lauriejim** [comment]
I close this issue.
We did it to make the tuto simple.
Feel free to submit a PR if you want to add it.
