### ISSUE TITLE
Next tutorial?

### ISSUE THREAD

**Issue by decimoseptimo** [strapi/strapi-examples#31]
@pierreburgy Insteresting that you chose nuxt before next. Anyways, looking forward for a next.js-strapi tutorial that features authentication.

**Comment by pierreburgy** [comment]
Good idea @decimoseptimo!

Would you like to write it (even if it is much shorter that the Nuxt tutorial)?

**Comment by decimoseptimo** [comment]
In fact I just started exploring the possibilty to use next.js with strapi so I'm currently consuming the content I can find in this regard. I just don't have the expertise at the moment.

I did the same in a past project, I explored the possibilty to use gatsby and strapi for the first time. For that you had an official tutorial which was one of the keys for me to get in.

**Comment by PDS42** [comment]
@decimoseptimo were you able to find good resources to use strapi with next? If so, please share them! :)

**Comment by NickBolles** [comment]
Also interested in using next with strapi. 

Next-auth has some good examples, and really is just a wrapper for express.js and passport authentication, but it adds client and server side methods that make sign-in easy. 

It sounds like it's at least possible. So I think I'm going to prototype something in the coming weeks maybe we can go from there? 

Let me know if anyone has any tips or tricks to help me get started.

**Comment by ryanbelke** [comment]
Following, looking into next.js and strapi also

**Comment by pierreburgy** [comment]
A Next article will be published in the next few weeks :)

Your articles are still welcomed.

**Comment by Gillinghammer** [comment]
Just coming across this page in my search for a next + strapi tutorial. 

+1 for that - wondering if @pierreburgy has an update?

**Comment by ryanbelke** [comment]
@Gillinghammer I re-created Pierre's Nuxt + Strapi tutorial in NextJs and the source repo can be viewed here: https://github.com/ryanbelke/strapi-next

There is a tutorial folder in that repo that has setup instructions and some main points to get started. 

I am working on the final writeup now and will be ready to post in the next couple of days. Let me know if you have any questions.Once the writeup is finished I will re-post here as well

**Comment by NickBolles** [comment]
I also have a next-middleware that I developed locally. It makes setting up next as simple as `strapi new app`, make a pages directory, and run strapi with `strapi start`  

The middleware delegates everything to strapi, and if the request is still 404, passes it to next to handle. 

Checkout the PR here: https://github.com/strapi/strapi/pull/2125

**Comment by NickBolles** [comment]
There is now a tutorial here: https://blog.strapi.io/strapi-next-setup/
