### ISSUE TITLE
Route "/Admin" is not showing and no data is being imported on start of server. 

### ISSUE THREAD

**Issue by stevenanthonyrevo** [strapi/strapi-examples#32]
**Node.js version**: v9.3.0

**npm version**: 5.6.0

**Strapi version**: 3.0.0-alpha.12.7.1

**Operating system**: Mac OS Sierra 10.12.6

**Which example is causing problem?**
Cheesecake

**Do you want to request a *feature* or report a *bug*?**
I see this as a bug, would be helpful to include more documentation on configuration of mongodb.  

**What is the current behavior?**
Starting the server with npm install & start. No admin panel is showing up and data is not being imported into my mongodb instance localhost. Appears to me like a bug. 

**If the current behavior is a bug, please provide the steps to reproduce the problem**
```
      git clone git@github.com:strapi/strapi-examples.git
      npm install && npm start 
      mongo 
      use cheesecakes
```
**What is the expected behavior?**
```
[2018-07-11T20:06:56.048Z] debug GET /cake/count (24 ms)
TypeError: Cannot read property 'policy' of null
    at module.exports (/../strapi-examples/cheesecakes/plugins/users-permissions/config/policies/permissions.js:50:18)
    at <anonymous>
TypeError: Cannot read property 'policy' of null
    at module.exports (/../strapi-examples/cheesecakes/plugins/users-permissions/config/policies/permissions.js:50:18)
    at <anonymous>
[2018-07-11T20:06:56.052Z] debug GET /info (21 ms)
[2018-07-11T20:06:56.052Z] debug GET /cake?_sort=id&_start=0&_limit=3 (14 ms)
```

Thank you for any help! Happy Coding!

**Comment by delkov** [comment]
Have same issue.
Go to mongo and make
db['users-permissions_permission'].updateMany({}, {$set: {enabled: true}})

**Comment by lauriejim** [comment]
I update the app to `alpha.13` and it fix this issue https://github.com/strapi/strapi-examples/commit/e5a3f8d13164930e7ecbba5867fbb08a64a8e697

**Comment by sinanerdem** [comment]
Hello,

I am using alpha.14. issue still exists.
