### ISSUE TITLE
cheesecakes example fails to run

### ISSUE THREAD

**Issue by mnlbox** [strapi/strapi-examples#33]
**Node.js version**:
9.0.0
**npm version**:
5.1.1
**Strapi version**:
3.0.0 alpha 12.7 globally and 3.0.0 alpha 12.3 for project (strapi-examples/cheesecakes current version)
**Operating system**: Linux

**Which example is causing problem?**
cheesecakes
**Do you want to request a *feature* or report a *bug*?**
report a *bug*
**What is the current behavior?**
Can't run example.
**If the current behavior is a bug, please provide the steps to reproduce the problem**
* Clone this repo
* `cd cheesecakes`
* `npm install`
* `strapi start`

And it's my terminal output:
```
[2018-07-12T06:56:16.192Z] debug Server wasn't able to start properly.
(hook:mongoose) takes too long to load
```
**What is the expected behavior?**

**Comment by mnlbox** [comment]
@soupette @lauriejim

**Comment by lauriejim** [comment]
I just update the app to `alpha.13`.

Can you try `npm start` instread of `strapi start`. If there is a difference between Strapi version of your app and your global install, conflicts can happen if you start the app with `strapi start`.

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any update about it.
