### ISSUE TITLE
How to make a dropdown from form.json

### ISSUE THREAD

**Issue by AndrewMerke** [strapi/strapi-examples#41]
Hello I am trying to learn about React-Redux authentications with JWT and yours examples works perfectly for me. But I have one question, how to make a dropbox with different value from yours form.json file. For example I want to add country to register formType. How to make dropdown of every country and make dropdown of them?

**Comment by soupette** [comment]
Well the idea of this file is to map an input with a type.
So you'll need to create a `DropDownInput` and add it to the InputsIndex, with the needed data.
Then it should works

**Comment by AndrewMerke** [comment]
But lets say I want Input and DropDownInput in random order, maybe you could suggest me how to achieve this?

**Comment by AndrewMerke** [comment]
Yes, something like that

**Comment by soupette** [comment]
You just need a shuffle algorithm then

**Comment by AndrewMerke** [comment]
Maybe you have an example in you directory with this?

**Comment by soupette** [comment]
I can provide some pseudo-code if you want.
If I do understand it well you want to 
- select a country => display a new input to select for example the state and so one?

**Comment by AndrewMerke** [comment]
Lets say, I have a form.json of 5 fields, 2 of them are dropdowns

**Comment by AndrewMerke** [comment]
I almost did everything, maybe you could provide simple dropdown pseudo-code. Like how to pass value and use it with
