### ISSUE TITLE
Getting 400 Bad Request for detail page on react-apollo example

### ISSUE THREAD

**Issue by mateodelnorte** [strapi/strapi-examples#42]
**Node.js version**:

10

**npm version**:

**Strapi version**:

3 alpha 14

**Operating system**:

mac

**Which example is causing problem?**

react-apollo

BUG

**What is the current behavior?**

visiting the detail page (http://localhost:3001/form/product/5b856a99fb67e97163d6c23a) by clicking on a line item results in the following error: `Error: Error: Network error: Response not successful: Received status code 400`

**If the current behavior is a bug, please provide the steps to reproduce the problem**

create a new product line item. click the product line item. 

**What is the expected behavior?**

should show detail page.

**Comment by soupette** [comment]
Can you pull master and tell me if it still occurs?

**Comment by mateodelnorte** [comment]
I'm sure it will. You made the same change to fix I made locally.
