### ISSUE TITLE
react-apollo __typename : "Product"

### ISSUE THREAD

**Issue by Foundj** [strapi/strapi-examples#44]
**Strapi version**:
v3.0.0-alpha.14

**Which example is causing problem?**

http://localhost:3000/form/product/1 
this edit page tap to submit is wrong!
because __typename : "Product" in query(data[params.contentType] )
How do I solve this problem?

**Comment by lauriejim** [comment]
I am closing this issue because we don’t have any updated/needed information regarding it.
Will reopen it if activity come back.
