### ISSUE TITLE
Log in with Facebook not working

### ISSUE THREAD

**Issue by M1chaelTran** [strapi/strapi-examples#45]
**Node.js version**:
v8.10.0
**npm version**:
5.6.0
**Strapi version**:
3.0.0-alpha.14.1.1
**Operating system**:
OSX

**Which example is causing problem?**
`login-react` and `react-apollo`
**Do you want to request a *feature* or report a *bug*?**
yes, I believed this is a bug🐛
**What is the current behaviour?**
I get a 400 bad request
```
{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.form.error.email.taken"}]}]}
```
**If the current behaviour is a bug, please provide the steps to reproduce the problem**
- Start any of the app listed above
- setup facebook login provider as per documentation
- start strapi `strapi start` and start react app `yarn start`
- open browser `http://localhost:3000/auth/login`
- the first-time login with Facebook works as expected.
- log out
- log in with facebook again
- receive error instead

***Things I've tried***
- I have not tried with other social networks, but I suspect the same error will occur.
- I have looked at the other issues logged with similar error message. However, they don't seem to be related as this seems to work the first time but not subsequent login.
- Toggling off `One account per email address` will throw 
`{"statusCode":400,"error":"Bad Request","message":{"message":"This username is already taken","field":["username"]}}` which make sense
- Also toggling off `Enable sign-ups` will give this error
`{"statusCode":400,"error":"Bad Request","message":[{"messages":[{"id":"Auth.advanced.allow_register"}]}]}` which should not be the case since I'm not trying to register a new user but log in with an existing user.
- It works if I delete the user from [strapi admin](http://localhost:1337/admin/plugins/content-manager/user?source=users-permissions) and then try log in with facebook again (but only first time)
- Tried local login with the Facebook user email with an invalid password, I get this error
`{"statusCode":400,"error":"Bad Request","message":"This user never set a local password, please login thanks to the provider used during account creation."}` seems valid

**What is the expected behaviour?**
log in with facebook should work and not throw error

**Comment by soupette** [comment]
Did you add some required field to the user model?

**Comment by M1chaelTran** [comment]
no, this is all straight up fresh from the start for strapi and the examples.

**Comment by soupette** [comment]
Can you try by following this [documentation](https://github.com/strapi/strapi/blob/enhancement/providers-use/docs/3.x.x/en/guides/authentication.md#enabling-facebook-provider) it was working a month ago and the configuration can be tricky...

**Comment by M1chaelTran** [comment]
I use that doc to double check everything I have done and yes, everything I have done matches up with the doc. 
If you are saying it works for you, then there must be some special settings or code change that doesn't exists in the example?

**Comment by lauriejim** [comment]
I just follow instructions with fresh new app of Strapi and it works well.
