### ISSUE TITLE
Jekyll + Strapi Build Warning: Layout 'default' requested in home.html does not exist.

### ISSUE THREAD

**Issue by realmarc** [strapi/strapi-examples#48]
**Node.js version**:
v10.11.0
**npm version**:
6.4.1
**Strapi version**:
3.0.0-alpha.14.2
**Operating system**:
Debian Stretch 64Bit

**Which example is causing problem?**
Jekyll + Strapi  
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Jekyll Console says: Build Warning: Layout 'default' requested in home.html does not exist.
**If the current behavior is a bug, please provide the steps to reproduce the problem**
My Jekyll is jekyll 3.8.4 I receive the error message posted below and the template minima won't be shown with the posts. I do only see the title "Posts" and I need to navigate to localhost:4000/home.html to see it. This seems to be more a Jekyll problem than a Strapi problem I guess? 
**What is the expected behavior?**
It won't say that and it will work I guess.

**Comment by jbrew30** [comment]
Add this to the top of your home.html

<img width="175" alt="Screen Shot 2021-02-15 at 1 34 40 PM" src="https://user-images.githubusercontent.com/22452733/107982729-945d8f80-6f92-11eb-8280-f56f37217bb0.png">
