### ISSUE TITLE
clarification about creating many to many using the content type builder

### ISSUE THREAD

**Issue by cocodrino** [strapi/strapi-examples#56]
hello guys, I was seeing that the content type builder allows you to create many to many relationships, since to do this you need an intermediate table, is it possible to create this relationship using the content type builder? no need for code or configuration? is there any guide to do this?

I suppose there must be a convention regarding the names of the columns, for example, I have the table article and tag, I created a content type called article_tag which will work as junction table and I try to set the id of the article with the column article_id of my junction table but the system does not allow me to do it.

![image](https://user-images.githubusercontent.com/616412/47611463-7b84e500-da3c-11e8-83c3-deab314ae895.png)

Any guide will be appreciate...I'm using postgresql...

thank you!!!

**Comment by lauriejim** [comment]
Strapi will automatically generate all the stuff to make the relation work.

**Comment by lauriejim** [comment]
In your **Article** model you set `tags` and in you **Tag** models you set `articles`

**Comment by rkneel123** [comment]
can  we modify the junction table if we want to add another field in this table?

**Comment by Ghospel** [comment]
> can we modify the junction table if we want to add another field in this table?

I would like to know this aswell

**Comment by EndlessBox** [comment]
i would love to know this too !
