### ISSUE TITLE
Upgrade Gatsby Example to use the latest version: v2

### ISSUE THREAD

**Issue by mccrodp** [strapi/strapi-examples#58]
**Node.js version**:
ANY

**npm version**:
ANY

**Strapi version**:
Latest

**Operating system**:
N/A

**Which example is causing problem?**
Gatsby Example: https://github.com/strapi/strapi-examples/tree/master/gatsby-strapi-tutorial/blog

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The examples use Gatsby v1, but v2 is the latest with many improvements. Is there a plan to upgrade to Gatsby v2 or do you have a recommended resource for Strapi with that?

**Comment by lauriejim** [comment]
Thank you for this feedback.
Actually it's not plan to work on it.
Feel free to submit a PR.

**Comment by mccrodp** [comment]
Thanks for letting me know it's not on the roadmap. If I go forward with this approach, I'll submit a PR. Cheers. In the meantime, if anything changes and you work on this, please ping on this issue. Thanks
