### ISSUE TITLE
nuxt-strapi: strapi sdk.js throw error

### ISSUE THREAD

**Issue by wemod123** [strapi/strapi-examples#61]
**Node.js version**: v 11.0.0
**npm version**: v 6.4.1
**Strapi version**: 3.0.0-alpha.14.5
**Operating system**: Ubuntu 18
**Example of : nuxt-strapi-deliveroo-clone-tutorial**

**Isuse:**
following illustration in readme, and issues on browser localhost:3000:

![image](https://user-images.githubusercontent.com/26819270/48670728-815f7900-eb57-11e8-96a2-81be018c00bd.png)

backend had being running well on localhost:1337, and api access tested with public user successfully;

**What is the expected behavior?**

**Comment by Phatza** [comment]
Hi guys,
same problem here.
@lauriejim Any idea ?

Thanks

**Comment by Phatza** [comment]
Hi,
This problem is related to mysql/mariadb.
I've tested using mongoDB with no errors.

**Comment by diacu** [comment]
I'm using it with MongoDB and I get this error. 
I my case, issue appears when having nuxt set with SSR. If you navigate using the router, it works well. If you access the page via url or refresh it, it gives this error.
I think it has to do with the fact that call is made from server.. From what I can tell, in the last case there is no OPTIONS request and strapi returns access denied response
