### ISSUE TITLE
Submit() is not responding when navigating in login area

### ISSUE THREAD

**Issue by cosydney** [strapi/strapi-examples#64]
**Node.js version**: v10.13.0
**npm version**: 6.5.0
**Strapi version**: 3.0.0-alpha.16
**Operating system**: MAC OS Sierra
**Which example is causing problem?**: react-login-front-end-app
**Do you want to request a *feature* or report a *bug*?** report a bug

**What is the current behavior?**
When logging in if a user clicks on Forgot Password and comes back to Ready to Sign in submit isn't responding anymore.

**If the current behavior is a bug, please provide the steps to reproduce the problem**
git clone project. Npm i. Npm Start
Before logging in navigate to Forgot Password and then navigate to Ready to sign in by clicking on links.

**What is the expected behavior?**
Expected behavior is to be able to sign in or get a response from server in the console.

**Comment by cosydney** [comment]
Seems to come from Saga.js, if I comment this line out it works but may be I should be calling that function on login success ? 
```  yield cancel(submitWatcher);```

**Comment by lauriejim** [comment]
This one https://github.com/strapi/strapi-examples/tree/master/login-react?

**Comment by cosydney** [comment]
Yes this one @lauriejim

**Comment by soupette** [comment]
@cosydney if you feel like fixing it I would really appreciate, otherwise I will take a look at it this week.

**Comment by cosydney** [comment]
looking again I might have a fix

**Comment by cosydney** [comment]
https://github.com/strapi/strapi-examples/pull/66
