### ISSUE TITLE
Undefined binding(s) detected when compiling SELECT query

### ISSUE THREAD

**Issue by Andrew1325** [strapi/strapi-examples#70]
**Node.js version**:
10.14.2
**npm version**:
6.4.1
**Strapi version**:
3.0.0-alpha.21
**Operating system**:
macOS 10.14

**Which example is causing problem?**
I'm following the nuxt/deliveroo tutorial and am up to creating dishes but got a "Cannot read property 'dishes' of null" error which I traced to the graphql query:

```
query {
  restaurant(id: "1") {
    id
    name
    dishes {
      id
      name
      description
      price
      image {
        url
       }
    }
  }
}
```

When run in playground this returns an error:

"message": "Undefined binding(s) detected when compiling SELECT query: select `restaurants`.* from `restaurants` where `restaurants`.`id` = ? limit ?",

I have discovered that any query with an attribute, user(id: "1") or dish(id:"1") return the same error.

I am using a mysql database. The tables are all there and have data in them, just can't get these queries to work.

Something like:

```
query {
	restaurants {
    name
  }
}
```

works fine.

**Comment by TetHat** [comment]
Having the same issue here on Strapi version 3.0.0-alpha.22. The referenced issue #2396 (which was fixed in alpha 22) appears to be a different issue entirely since this is still broken in alpha 22.

**Comment by scorpionking90** [comment]
I am also facing the same issue. Please provide solution at the earliest as it is stopping me alot. Thanks in advance.

**Comment by thomaskvael** [comment]
I am also having the same problem. The example from Strapi doc is not working
[https://strapi.io/documentation/3.x.x/guides/graphql.html#query-api](https://strapi.io/documentation/3.x.x/guides/graphql.html#query-api)
Only workaround is to use a where clause but that returns an array of posts instead of a single post.

**Not working:**
```
query {
    post(id: "3") {
      title
      byline
      lead
      content
    }
}
```

Returns error:
"Undefined binding(s) detected when compiling SELECT query: select `posts`.* from `posts` where `posts`.`id` = ? limit ?"

**Workaround:**
```
query {
    posts(where: {id:"3"}) {
      title
      byline
      lead
      content
    }
}
```
Node: v10.15.0
Npm: 6.4.1
Strapi: 3.0.0.alpha 21
OS: Windows 10
Database: MySQL

**Comment by kenberkeley** [comment]
Same issue
![image](https://user-images.githubusercontent.com/13287948/52774868-676bfe80-3092-11e9-8a08-8d89f761a6f3.png)

**Comment by genesos** [comment]
Alpha 23.1, same issue too.
But I found the error point maybe.

Changing `plugins/graphql/service/Query.js` 
from
```            value: {
              ...this.convertToParams(_.omit(_options, 'where')),
              ..._options.where,
```
to
```            value: {
              ...this.convertToParams(_.omit(_options, 'where')),
              ..._options,
              ..._options.where,
```
makes working right temporary.

**Comment by notapatch** [comment]
Workaround is to use mongodb - in stage 1 - setup they use MongoDB (recommended).

Got here because I had the same issue, but using Postgres. I did not get this problem when using MongoDB.

**Comment by lauriejim** [comment]
I close this issue, can you check on the mono repo if this issue exist.
It's not related to the example but look like related to the GraphQL plugin.
