### ISSUE TITLE
error on npm install

### ISSUE THREAD

**Issue by DanLahav-TG** [strapi/strapi-examples#71]
**Node.js version**:
10*
**npm version**:
6*
**Strapi version**:

**Operating system**:
ubonto 18.04

**Which example is causing problem?**
react-login-front-end-app

 ⚠ The `/home/linuxdan/Downloads/strapi-examples/login-react/react-login-front-end-app/node_modules/imagemin-pngquant/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/home/linuxdan/Downloads/strapi-examples/login-react/react-login-front-end-app/node_modules/imagemin-pngquant/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm WARN react-boilerplate@ No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linuxdan/.npm/_logs/2019-02-04T15_12_11_205Z-debug.log

**Comment by lauriejim** [comment]
Hello, please follow the issue template.

A proper issue submission let's us better understand the origin of your bug and therefore help you.

I will reopen your issue when we receive the issue following the template guidelines.

Please update the issue.

Thank you.

> This is a templated message
