### ISSUE TITLE
label:app:cheesecake not working

### ISSUE THREAD

**Issue by barak-haviv** [strapi/strapi-examples#72]
**Node.js version**:
v10.13.0

**npm version**:
6.7.0

**Strapi version**:

**Operating system**:
mac Mojave

**Which example is causing problem?**
cheesecake

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I could installed the app an the admin is work fine
Also db created in my mongodb instance.
BUT I see almot empty page only sort by price dropdown and that's it.
![screen shot 2019-02-05 at 15 54 53](https://user-images.githubusercontent.com/2076998/52277882-67ffe900-295e-11e9-8eba-7b015a3d3cf8.png)

**If the current behavior is a bug, please provide the steps to reproduce the problem**

**What is the expected behavior?**

**Comment by lauriejim** [comment]
Hello @barak-haviv !

Did you open permission as listed in the readme ?

**Comment by barak-haviv** [comment]
Sorry I missed this one.
It is working now.
Thanks

**Comment by hamedhossani** [comment]
Hello @barak-haviv
How To change permission?

**Comment by hamedhossani** [comment]
When i opened ```http://localhost:1337/admin``` in browser
it's not show login page or menu user & permission .
How can i change permission? is something wrong?
