### ISSUE TITLE
Manage Local State with Apollo Client? (react-apollo)

### ISSUE THREAD

**Issue by puneetverma05** [strapi/strapi-examples#75]
Can we manage Local State with Apollo Client?
It is mentioned that Mutations are not supported.

**Comment by puneetverma05** [comment]
**Need Clarification**,
In the Docs, it says we can mutate...
https://strapi.io/documentation/3.x.x/guides/graphql.html#update-an-existing-entry

**Comment by soupette** [comment]
Well it wasn't supported when we developed the app, though it should be possible now since we support mutations. Here's the [Apollo's documentation on local state](https://www.apollographql.com/docs/react/essentials/local-state)
