### ISSUE TITLE
Error on npm run dev

### ISSUE THREAD

**Issue by TengkuFathullah** [strapi/strapi-examples#79]
**Node.js version**:
v10.15.0
**npm version**:
6.9.1-next.0
**Strapi version**:
-
**Operating system**:
Windows 7 Ultimate x64

**Which example is causing problem?**
nuxt-strapi-deliveroo-clone-tutorial

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
x error Error: Plugin not found: D:\[GitLab]\strapi-examples\nuxt-strapi-deliveroo-clone-tutorial\client\.nuxt\bootstrap-vue.js
at Promise.all.plugins.map (D:\[GitLab]\strapi-examples\nuxt-strapi-deliveroo-clone-tutorial\client\node_modules\nuxt\dist\nuxt.js:4011:15)

if I remove "modules: ['bootstrap-vue/nuxt']" in nuxt.config.js, above error is gone but
I will get another error which is.

nuxt-strapi-deliveroo-clone-tutorial\client\node_modules\snapdragon\lib\parser.js:473
   throw new Error('no parsers registered for: "' + self.input.slice(0, 5) + '"');

**If the current behavior is a bug, please provide the steps to reproduce the problem**
I just follow the step given.
cd nuxt-strapi-deliveroo-clone-tutorial
cd client
npm install
npm run dev

**Comment by lauriejim** [comment]
Hello! I just pulled and followed same instruction as you did and it works on my side.
