### ISSUE TITLE
TypeError: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by fonziemedia** [strapi/strapi-examples#81]
**Node.js version**: 10.4.1

**npm version**: 6.1.0

**Strapi version**: 3.0.0-alpha.24.1 (this is a frontend issue though)

**Operating system**: macOS Mojave

**Which example is causing problem?**
nextjs-react-strapi-deliveroo-clone-tutorial	

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I can run  'npm run dev' or 'npm start' without issues but when I open locallhost:3000 the page loads with 'error loading restaurants' and I get a server side typeError (see screenshot)
(no front end console errors)

**If the current behavior is a bug, please provide the steps to reproduce the problem**
cd frontend
npm install
npm run build
npm run dev or npm start

**What is the expected behavior?**
to run without errors

![Screenshot 2019-03-24 at 19 39 51](https://user-images.githubusercontent.com/9273990/54884202-633fb780-4e6e-11e9-9b3b-834361eabfd6.png)

**Comment by lauriejim** [comment]
Hello! It's because you don't have data in your application and because routes are not open in your admin panel.

Please I suggest you to follow the steps in the article linked to this example.

Let me know if it's ok after that.

**Comment by benjaminloeffel** [comment]
Hi @lauriejim  !

I've encountered the same issue as above on every render.

![2019-03-27_16-45-42](https://user-images.githubusercontent.com/15696921/55091063-73df7000-50b0-11e9-8b3d-35099cce8b59.png)

Could you clarify what causes this issue and how this can be resolved and avoided in the future?

Thanks & Regards

**Comment by fonziemedia** [comment]
Hi @benjaminloeffel 

As @lauriejim you need to have data and open the routes in the admin area (permissions).

Check the tutorial for more info on the permissions you should grant.

Hope this helps and thanks @lauriejim for your reply.

**Comment by benjaminloeffel** [comment]
Hi @fonziemedia !

In my **Public** & **Authenticated** Roles & Permissions all Content Types have `find` & `findone` checked.

![image](https://user-images.githubusercontent.com/15696921/55095054-d0925900-50b7-11e9-974a-4cc8497f7f6c.png)

The routes are open and I have added data to all content types. 😞

**Comment by benjaminloeffel** [comment]
Hi @fonziemedia !

Data has been added to all Content Types and under **Roles & Permissions** in both the **Authenticated** & **Public** the **Userspermissions** `getroutes` checkbox is ticked.

![image](https://user-images.githubusercontent.com/15696921/55096050-7b574700-50b9-11e9-8eb9-905df7ea465e.png)

The issue still occurs. :pensive: !

**Comment by fonziemedia** [comment]
@benjaminloeffel,

You don't need to change the users permissions but the 'application' permissions for dish, order and restaurants as per the instructions on https://blog.strapi.io/strapi-next-setup/

**Comment by benjaminloeffel** [comment]
@fonziemedia & @lauriejim 

Yes, I was following that tutorial and went over it a couple of times because I was unsure whether or not I had missed something.

I've followed the instructions found on the tutorial as per below:

> Navigate to the Roles & Permissions section of the admin plugin (http://localhost:1337/admin/plugins/users-permissions).
Click on the Public role.
Tick the find and findone checkboxes of the Restaurant section.
Save.
Important: do the same thing for the authenticated role.

![image](https://user-images.githubusercontent.com/15696921/55141525-daa96b80-513a-11e9-8d42-155f843ee4db.png)

The data is received and and displaying properly for me, however the **TypeError** still gets printed to the console.

**Comment by lauriejim** [comment]
Thank you @fonziemedia for the feedback.
I close this issue. If it works for you @fonziemedia it have to work for you @benjaminloeffel .
You probably miss something.

**Comment by benjaminloeffel** [comment]
It turns out that the issue I was experiencing above occurred due to an issue in the "next-apollo" dependency: 

[Cannot read property 'pathname' of undefined](https://github.com/adamsoffer/next-apollo/issues/31#issue-430234455)
