### ISSUE TITLE
Google setup

### ISSUE THREAD

**Issue by DevMA523** [strapi/strapi-examples#85]
Hi,
The Google+ closed. The Google+ API will also die.

What's about this page :
https://github.com/strapi/strapi-examples/blob/master/login-react/doc/google_setup.md

How to setup google now without the Google+ API ? :)

**Comment by lauriejim** [comment]
Hello! we have an issue here https://github.com/strapi/strapi/issues/2660
But it's not a topic we are working on.
We are waiting a PR from the community on this point.

**Comment by DevMA523** [comment]
Thank you :)
