### ISSUE TITLE
Content type builder 

### ISSUE THREAD

**Issue by adds08** [strapi/strapi-examples#88]
Hey guys !

I really like Strapi but I am scratching my head with SQL-db relation.

So a user can create many "Messages"
but user can subscribe to only one message from other User

In SQL I have 3tables for it but how to build it using the content-type-builder

Thank you

**Comment by lauriejim** [comment]
Hello! 

You will have to create 2 relations.
One for the "creation" User(messages) <- oneToMany -> Message(author)
And one for "subscription" User(subscription) <- manyToOne -> Message(subscripters)
