### ISSUE TITLE
I'm getting these errors on gatsby develop for gatsby-source-strapi plugin

### ISSUE THREAD

**Issue by lorenafoia** [strapi/strapi-examples#9]
Hey guys, whenever I run `gatsby develop`, these errors and warnings shows up:

```
⠁ Starting to fetch data from Strapi
Starting to fetch data from Strapi
error Plugin gatsby-source-strapi returned an error


  Error: Request failed with status code 401
  
  - createError.js:16 createError
    [blog]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [blog]/[axios]/lib/core/settle.js:18:12
  
  - http.js:192 IncomingMessage.handleStreamEnd
    [blog]/[axios]/lib/adapters/http.js:192:11
  
  - next_tick.js:152 process._tickCallback
    internal/process/next_tick.js:152:19

warning The gatsby-source-strapi plugin has generated no Gatsby nodes. Do you need it?

```  
and then:

```
GraphQL Error There was an error while compiling your site's GraphQL queries.
  Invariant Violation: GraphQLParser: Unknown field `allStrapiArticle` on type `RootQueryType`. Source: document `IndexQuery` file: `GraphQL request`.

```

I followed the entire tutorial but got these errors. I tried just copy and paste all the code, to avoid typos, but the errors persisted. I also got the same errors when I cloned the project and ran all the npm install and stuff. :T

**Comment by pierreburgy** [comment]
This is due to the permissions set in your Strapi project. 

Please double check the [step Allow Access](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/#allowaccess) in the tutorial and take a look at the [comments in the article](https://blog.strapi.io/building-a-static-website-using-gatsby-and-strapi/#disqus_thread).

**Comment by lorenafoia** [comment]
Oh, ok...  I had set permission only for the articles, forgot about User. Thank you!

**Comment by pierreburgy** [comment]
You are welcome. Have fun using Gatsby and Strapi!
